alias r='ranger'
alias ctc='pwd | xclip -selection clipborad'
alias al='rofi -show drun -show-icons -dpi 192'
alias token='cat ~/Documents/tokens | xclip -selection clipbord'
alias config='/usr/bin/git --git-dir=/home/monzer/dotfiles/ --work-tree=/home/monzer'
alias teco='tty-clock -C 4 -c'
