#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

${HOME}/.config/polybar/launch.sh &
compton &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#a6beef" 
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura desktop='^5' follow=on state=tiled

setxkbmap -option grp:alt_shift_toggle ar,us &

xsetroot -cursor_name left_ptr

${HOME}/.fehbg
